@clothes_backend_HostAddress = http://localhost:5295

GET {{clothes_backend_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{clothes_backend_HostAddress}}/api/products/id?id=5
Accept: application/json
###
POST {{clothes_backend_HostAddress}}/api/product-variants
Accept: application/json
{
  "id":0,
  "product_id":4,
  "price":2,
  "old_price":10,
  "quantity":4,
  "options":1,
}